name: avatars-api
region: fra
services:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: DiceBear/avatars-api
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    name: avatars-api
    routes:
      - path: /
    run_command: yarn start
